version: "3.2"
services:
  mysql:
    restart: always
    container_name : mysql-docker
    image: mysql
    environment:
       MYSQL_ROOT_PASSWORD: shalini123
       MYSQL_DATABASE : institution
    ports:
      - "6033:3306"
    volumes:
     - ./mysql-data:/var/lib/mysql
  studentapplication:
    container_name : studentapplication
    restart: always
    image: springboot-application-one 
    ports:
      - "8081:8081"
    depends_on:
      - mysql
  StudentApplication2:
    container_name : studentapplicationtwo
    image: springboot-application-two 
    ports:
      - "8082:8082"
    depends_on:
      - studentapplication
